void population() {
  buttonX1 = displayWidth*1/5;
  buttonY1 = displayHeight*2/5;
  buttonWidth = displayWidth*1/5;
  buttonHeight = displayHeight*1/5;
  rectX = displayWidth*1/10;
  rectY = displayHeight*1/10;
  rectWidth = buttonWidth;
  rectHeight = buttonHeight;
  circleX = displayWidth*8/10;
  circleY = displayHeight*2/10;
  circleDiameter = displayWidth*1/10;
  } //End Population
